services:
  multilingual-bookstore:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./multilingual-bookstore.db:/src/multilingual-bookstore.db
    ports:
      - "80:8000"
    expose:
      - 8000